version: '3.8'

services:
  jboss6:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
      - "8080:8080"
      - "9990:9990"
      - "80:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GpoDocker01@
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
